name: 'demo-action'

description: 'it is a simple composite file for greet someone'

inputs:
  whom-to-greet:  # Name of the input
    description: 'name of the person you want to greet'
    required: false
    default: 'hellow-world'
  
outputs:
  demo-outpu:
    description: 'Result from the costum action'
    value: ${{ steps.set_output.output.result }}


runs:
  using: 'composite'

  steps:
    - name: greet
      run: echo "Hello ${{ inputs.whom-to-greet }}"
      shell: bash

    - name: set output
      id: set_output
      run: echo "result=success" >> $GITHUB_OUTPUT
      shell: bash

