name: Reusable Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Print Message
        run: echo "Running reusable workflow"

      - name: Build
        run: echo "Building application..."