name: cache

on: workflow_dispatch

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: cache data
        id: cache
        uses: actions/cache@v5
        with:
          path: data
          key: my-cache-v1

      - name: time consuming activity
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "no cache yet, slow operation started!!"
          sleep 25
          mkdir data
          echo "some data" > /data/text.txt
          echo "slow operation completed"

      - name: read the file
        run: cat data/text.txt







