name: demo composite action

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: run the demo action
        id: demo
        uses: ./.github/actions/demo/actions.yaml
        with:
          whom-to-greet: "Tejasthu"

      - name: display demo output
        run: echo "output= ${{steps.demo.outputs.result}}"