name: demo composite action

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: run the demo action
        id: demo
        uses: ./.github/actions/demo
        with:
          whom-to-greet: "Tejasthu"

      - name: display demo output
        run: echo "output=${{ steps.demo.outputs.result }}"