name: variables

on:
  workflow_dispatch:
        inputs:
          environment:
            description: 'Application environment'
            required: true
            default: 'test'
            type: choice
            options:
              - dev
              - test
              - prod
          version:
            description: 'Application version'
            required: true
            default: 'v1.0.0'

env:
  GLOBAL_ENV: "1 tier application"


jobs:
  job1:
    runs-on: ubuntu-latest
    
    env: 
      JOB1: "2 tier appli0cation"

    steps:
      - name: show the inputs
        run: |
          echo  "environment is : ${{ inputs.environment }}"
          echo  "version is : ${{ inputs.version }}" 

      - name: global variable
        run: |
          echo  "global variable is : $GLOBAL_ENV" 
      
      - name: JOB1 variable
        run: |
          echo  "JOB1 variable is : $JOB1" 

  job2:
    runs-on: ubuntu-latest
    
    env:
      JOB2: "Monolithic application"
    steps:
      - name: JOB2 variable
        run: |
          echo  "JOB2 variable is : $JOB2"
